import type {
  BOARD,
  BOARD_DETAILS,
  CARD,
  LIST,
  MEMBER,
  USER,
  WORKSPACE,
} from "./types";

// Dummy user
export const dummyUser: USER = {
  id: "member-1",
  name: "Sai Krishna Dandu",
  email: "228r5a0407@gmail.com",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sai",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

// Dummy members
export const dummyMembers: MEMBER[] = [
  {
    id: "member-1",
    name: "Sai Krishna Dandu",
    email: "228r5a0407@gmail.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sai",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "member-2",
    name: "John Doe",
    email: "john@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "member-3",
    name: "Alice Johnson",
    email: "alice@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alice",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Dummy cards
export const dummyCards: CARD[] = [
  {
    id: "card-1",
    title: "Setup project structure",
    description: "Initialize the project with necessary folders and files",
    listId: "list-1",
    boardId: "board-1",
    position: 0,
    status: "ACTIVE",
    dueDate: null,
    startDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: "member-1",
    assignees: [dummyMembers[0]],
    labels: [],
    attachments: [],
    checklists: [],
    comments: [],
  },
  {
    id: "card-2",
    title: "Design database schema",
    description: "Create the Prisma schema for the database",
    listId: "list-1",
    boardId: "board-1",
    position: 1,
    status: "ACTIVE",
    dueDate: null,
    startDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: "member-1",
    assignees: [dummyMembers[1]],
    labels: [],
    attachments: [],
    checklists: [],
    comments: [],
  },
  {
    id: "card-3",
    title: "Implement authentication",
    description: "Add JWT-based authentication to the backend",
    listId: "list-2",
    boardId: "board-1",
    position: 0,
    status: "ACTIVE",
    dueDate: null,
    startDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: "member-1",
    assignees: [dummyMembers[1], dummyMembers[2]],
    labels: [],
    attachments: [],
    checklists: [],
    comments: [],
  },
  {
    id: "card-4",
    title: "Build API endpoints",
    description: "Create REST API endpoints for boards and cards",
    listId: "list-2",
    boardId: "board-1",
    position: 1,
    status: "ACTIVE",
    dueDate: null,
    startDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: "member-1",
    assignees: [dummyMembers[0]],
    labels: [],
    attachments: [],
    checklists: [],
    comments: [],
  },
  {
    id: "card-5",
    title: "Create UI components",
    description: "Build React components for the frontend",
    listId: "list-3",
    boardId: "board-1",
    position: 0,
    status: "ACTIVE",
    dueDate: null,
    startDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: "member-1",
    assignees: [dummyMembers[2]],
    labels: [],
    attachments: [],
    checklists: [],
    comments: [],
  },
  {
    id: "card-6",
    title: "Setup drag and drop",
    description: "Implement drag and drop with dnd-kit",
    listId: "list-3",
    boardId: "board-1",
    position: 1,
    status: "ACTIVE",
    dueDate: null,
    startDate: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: "member-1",
    assignees: [dummyMembers[0]],
    labels: [],
    attachments: [],
    checklists: [],
    comments: [],
  },
];

// Dummy lists
export const dummyLists: LIST[] = [
  {
    id: "list-1",
    title: "To Do",
    boardId: "board-1",
    position: 0,
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cards: dummyCards.filter((card) => card.listId === "list-1"),
  },
  {
    id: "list-2",
    title: "In Progress",
    boardId: "board-1",
    position: 1,
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cards: dummyCards.filter((card) => card.listId === "list-2"),
  },
  {
    id: "list-3",
    title: "In Review",
    boardId: "board-1",
    position: 2,
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cards: dummyCards.filter((card) => card.listId === "list-3"),
  },
  {
    id: "list-4",
    title: "Done",
    boardId: "board-1",
    position: 3,
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cards: [],
  },
];

// Dummy boards
export const dummyBoards: BOARD[] = [
  {
    id: "board-1",
    title: "Trello Clone Project",
    workspaceId: "workspace-1",
    backgroundColor: "#0079bf",
    backgroundImageUrl: null,
    visibility: "PRIVATE",
    archived: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: "member-1",
  },
  {
    id: "board-2",
    title: "Marketing Campaign",
    workspaceId: "workspace-1",
    backgroundColor: "#519839",
    backgroundImageUrl: null,
    visibility: "PRIVATE",
    archived: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: "member-1",
  },
  {
    id: "board-3",
    title: "Product Roadmap",
    workspaceId: "workspace-1",
    backgroundColor: "#b04632",
    backgroundImageUrl: null,
    visibility: "WORKSPACE",
    archived: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: "member-1",
  },
];

// Dummy workspace
export const dummyWorkspace: WORKSPACE = {
  id: "workspace-1",
  name: "Personal Workspace",
  description: "My personal workspace for task management",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  createdBy: "member-1",
};

// Dummy board details
export const dummyBoardDetails: BOARD_DETAILS = {
  board: dummyBoards[0],
  lists: dummyLists,
  members: dummyMembers,
};
